### ISSUE TITLE
apparently you can no longer sync google acc through chromium

### ISSUE THREAD

**Issue by ethanj0hn** [abhinavpappu/cs225-potd-scraper#5]
https://stackoverflow.com/questions/67459316/enabling-chromium-to-sync-with-google-account/68674527#68674527

apparently you can no longer sync google account, so whenever code is run you get "`Error: You're either not logged in, not enrolled in CS 225, or enrolled in multiple CS 225s`" how would you change code s.t it opens up prairelearn, you sign in manually, then it scrapes?

**Comment by abhinavpappu** [comment]
Turns out this was due to some minor changes PraireLearn made, causing my program to think you're already logged in when you aren't. About to make a PR that will fix the sign in part, though not sure if there were any additional changes made to the POTD part that will cause it to break (not enrolled in course anymore so can't test)
